import { useMemo } from 'react'
import type { Filters } from './FilterBar'
import FilterBar from './FilterBar'
import MovieCard from './MovieCard'

interface RecommendationCard {
  id: string
  tmdb_id: number
  title: string
  year: number | null
  genres: string[]
  moods: string[]
  decade: string
  matchScore: number
  matchReason: string
  runtime: number | null
  posterUrl: string | null
  posterColor: string
}

interface RecommendationsSectionProps {
  username: string
  filters: Filters
  onFiltersChange: (f: Filters) => void
  recommendations: RecommendationCard[]
  statusMessage: string
  error: string | null
  onLoadMore: () => void
  isLoadingMore: boolean
}

export default function RecommendationsSection({
  username,
  filters,
  onFiltersChange,
  recommendations,
  statusMessage,
  error,
  onLoadMore,
  isLoadingMore,
}: RecommendationsSectionProps) {
  const filtered = useMemo(() => {
    return recommendations.filter((movie) => {
      if (filters.genre && !movie.genres.includes(filters.genre)) return false
      if (filters.mood && !movie.moods.includes(filters.mood)) return false
      if (filters.decade && movie.decade !== filters.decade) return false
      return true
    })
  }, [filters, recommendations])

  return (
    <section>
      <div className="px-6 py-4 border-b border-border">
        <div className="max-w-7xl mx-auto flex flex-wrap items-center gap-3">
          <span
            className="text-muted-foreground text-xs tracking-widest uppercase"
            style={{ fontFamily: 'var(--font-mono)', fontSize: '0.65rem' }}
          >
            Profile
          </span>
          <span
            className="text-primary text-sm font-medium"
            style={{ fontFamily: 'var(--font-mono)' }}
          >
            @{username}
          </span>
          <span className="text-border text-xs">/</span>
          <span
            className="text-muted-foreground text-xs"
            style={{ fontFamily: 'var(--font-mono)' }}
          >
            {recommendations.length > 0 ? `${recommendations.length} recommendations` : 'waiting for data'}
          </span>
        </div>
      </div>

      <div className="px-6 py-4 border-b border-border">
        <div className="max-w-7xl mx-auto">
          <p className="text-sm text-secondary-foreground" style={{ fontFamily: 'var(--font-sans)' }}>
            {statusMessage}
          </p>
          {error && (
            <p className="mt-2 text-sm text-primary" style={{ fontFamily: 'var(--font-mono)' }}>
              {error}
            </p>
          )}
        </div>
      </div>

      <FilterBar filters={filters} onChange={onFiltersChange} count={filtered.length} />

      <div className="max-w-7xl mx-auto px-6 py-8">
        {filtered.length === 0 ? (
          <div className="py-20 text-center">
            <p
              className="text-muted-foreground text-sm"
              style={{ fontFamily: 'var(--font-mono)' }}
            >
              {recommendations.length === 0
                ? 'Your recommendations will appear here once the sync finishes.'
                : 'No films match the current filters.'}
            </p>
            <button
              onClick={() => onFiltersChange({ genre: null, mood: null, decade: null })}
              className="mt-3 text-xs text-primary hover:opacity-80 transition-opacity underline underline-offset-2"
              style={{ fontFamily: 'var(--font-mono)' }}
            >
              clear all filters
            </button>
          </div>
        ) : (
          <div
            className="grid gap-5"
            style={{
              gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
            }}
          >
            {filtered.map((movie) => (
              <MovieCard key={movie.id} movie={movie} username={username} />
            ))}
          </div>
        )}
      </div>

      {filtered.length > 0 && recommendations.length > 0 && (
        <div className="px-6 pb-6 max-w-7xl mx-auto flex justify-center">
          <button
            onClick={onLoadMore}
            disabled={isLoadingMore}
            className="px-6 py-3 border border-border text-foreground text-sm font-medium rounded-sm
                       transition-all duration-200 hover:bg-secondary active:scale-[0.98]
                       disabled:opacity-40 disabled:cursor-not-allowed"
            style={{ fontFamily: 'var(--font-sans)' }}
          >
            {isLoadingMore ? 'Loading more films...' : 'Load more recommendations'}
          </button>
        </div>
      )}

      <div className="px-6 pb-10 max-w-7xl mx-auto">
        <p
          className="text-muted-foreground text-xs border-t border-border pt-6"
          style={{ fontFamily: 'var(--font-mono)' }}
        >
          Recommendations are generated by analyzing your Letterboxd diary and taste profile. Results update as your activity grows.
        </p>
      </div>
    </section>
  )
}
